"""Initial migration

Revision ID: bc9715193759
Revises: 
Create Date: 2024-05-22 12:15:04.306134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc9715193759'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipaddress', sa.String(length=39), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('up', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('notified', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ipaddress')
    )
    op.create_table('host_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('up', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['host.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('host_history')
    op.drop_table('host')
    # ### end Alembic commands ###
